### ISSUE TITLE
Stack Install failed on Windows 10 with ExitFailure 1

### ISSUE THREAD

**Issue by jdimyadi** [flaviusb/legalruleml-thinger#1]
[1 of 2] Compiling Main             ( C:\Users\user\AppData\Local\Temp\stack1960\postgresql-libpq-0.9.4.1\Setup.hs, C:\Users\user\AppData\Local\Temp\stack1960\postgresql-libpq-0.9.4.1\.stack-work\dist\5c8418a7\setup\Main.o )
[2 of 2] Compiling StackSetupShim   ( C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\Users\user\AppData\Local\Temp\stack1960\postgresql-libpq-0.9.4.1\.stack-work\dist\5c8418a7\setup\StackSetupShim.o )
Linking C:\Users\user\AppData\Local\Temp\stack1960\postgresql-libpq-0.9.4.1\.stack-work\dist\5c8418a7\setup\setup.exe ...
Configuring postgresql-libpq-0.9.4.1...
setup.exe: The program 'pg_config' is required but it could not be found.

**Comment by flaviusb** [comment]
This issue talks about how to install pg_config on Windows: https://github.com/lpsmith/postgresql-simple/pull/66

Does this fix the installation problem?

**Comment by jdimyadi** [comment]
No, that didn't help. The folder that contains pg_config.exe is in the system PATH, yet somehow the install procedure couldn't see it. But, I have managed to execute stack install right within the postgreSQL/9.5/bin/ folder.

**Comment by jdimyadi** [comment]
Git clone the repo again and execute stack install and this time it did it without error.

**Comment by flaviusb** [comment]
Wow that is weird. Shall I add that to the install doc as a possibly necessary procedure?

**Comment by jdimyadi** [comment]
Problem with postgresql connecting to the database

**Comment by flaviusb** [comment]
Is the database active? That is, Postgresql needs to be running to connect to.

**Comment by jdimyadi** [comment]
Reinstalled Postgres 10.5 and all is good.
