### ISSUE TITLE
SqlError when executing legalruleml-thinger-exe.exe db

### ISSUE THREAD

**Issue by jdimyadi** [flaviusb/legalruleml-thinger#2]
SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"Formula\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}

**Comment by flaviusb** [comment]
Is this after running `legalruleml-thinger-exe init DBNAME USER PASSWORD PORT` ?

**Comment by flaviusb** [comment]
(To initially set up the needed tables)

**Comment by jdimyadi** [comment]
Yes, the error was raised after running 'legalruleml-thinger-exe.exe db DBNAME USER PASSWORD PORT

**Comment by flaviusb** [comment]
Just clarifying, did you first run `legalruleml-thinger-exe.exe init ...` and not get any errors, and then run `legalruleml-thinger-exe.exe db ...` on the same database and get that error?

**Comment by jdimyadi** [comment]
I'll run through it again to see if I get an error for init

**Comment by jdimyadi** [comment]
Well, it seems to work now. I did notice the database must be started manually.
