### ISSUE TITLE
Init database

### ISSUE THREAD

**Issue by jdimyadi** [flaviusb/legalruleml-thinger#4]
Do we need to drop all tables manually before using legalruleml-thinger-exe to init the database?

**Comment by flaviusb** [comment]
Only if you already have stuff in the database that you don't want - init doesn't clear away anything, so it won't accidentally destroy any data you have. If you want an absolutely clean database, you can drop and then recreate the database.

**Comment by jdimyadi** [comment]
Cool. Thx
